export const mockUsers = {
  agent: {
    id: 'agent-001',
    name: 'Priya Sharma',
    email: 'priya@travels.co',
    phone: '+91 98765 43210',
    company: 'Horizon Travel Agency',
    role: 'agent',
  },
  driver: {
    id: 'driver-001',
    name: 'Ravi Kumar',
    email: 'ravi.driver@tajway.app',
    phone: '+91 91234 56780',
    licenseNumber: 'DL-09-2020-112233',
    role: 'driver',
  },
  owner: {
    id: 'owner-001',
    name: 'Amit Verma',
    email: 'amit@fleetpro.in',
    phone: '+91 99887 76655',
    company: 'FleetPro Mobility',
    fleetSize: 24,
    role: 'owner',
  },
};

export const mockBookings = [
  {
    id: 'BK-1001',
    title: 'Airport Transfer — Delhi',
    pickup: 'Connaught Place, New Delhi',
    drop: 'IGI Airport T3',
    date: '2026-09-18',
    time: '06:30 AM',
    vehicleType: 'sedan',
    passengers: 2,
    status: 'open',
    budget: 1800,
  },
  {
    id: 'BK-1002',
    title: 'Corporate Outstation',
    pickup: 'Gurgaon Cyber Hub',
    drop: 'Jaipur',
    date: '2026-09-20',
    time: '08:00 AM',
    vehicleType: 'innova',
    passengers: 5,
    status: 'quoted',
    budget: 9500,
  },
];

export const mockMarketBookings = [
  {
    id: 'MK-1001',
    name: 'Deepesh Dutta',
    company: 'Duttaluxurytravels',
    when: 'Tomorrow',
    time: '07:00 AM',
    from: 'Gurugram',
    to: 'Dehradun',
    pickupFrom: 'Gurugram, Haryana, India',
    dropTo: 'Dehradun, Uttarakhand, India',
    tripType: 'One Way',
    vehicle: 'INNOVA CRYSTA',
    vehicleType: 'innova',
    extras: 'with carrier, All inclusive',
    bookingType: 'Public Booking',
    secured: true,
    reviews: 26,
    rating: 5,
    partnerHidden: false,
    avatarInitials: 'DD',
    hasAvatar: true,
  },
  {
    id: 'MK-1002',
    name: 'Travel Partner',
    when: 'Sep 19, 2026',
    time: '07:01 AM',
    duration: 'for 2 Days',
    from: 'Gurugram',
    pickupFrom: 'Sector 43, Gurgaon, Haryana, India',
    tripType: 'Round Trip',
    vehicle: 'Ertiga',
    vehicleType: 'ertiga',
    notes:
      'pick up Gurgaon se Vrindavan Mathura Barsana all include parking extra',
    extras: 'All inclusive, Inc AC in plains, ret btao All include',
    bookingType: 'Public Booking',
    secured: true,
    reviews: 7,
    rating: 4.5,
    partnerHidden: true,
  },
  {
    id: 'MK-1003',
    name: 'Travel Partner',
    when: 'Today',
    time: '10:00 PM',
    from: 'T2 IGI Airport',
    to: 'Agra',
    pickupFrom: 'T2 IGI Airport',
    dropTo: 'Agra, Uttar Pradesh, India',
    tripType: 'One Way',
    vehicle: 'Sedan',
    vehicleType: 'sedan',
    extras:
      'Diesel, with carrier, All inclusive, jiski khali ho apna ret de cng bhale bhi le sakte h lekin cng ke liye gadi rukegi nhi',
    bookingType: 'Public Booking',
    secured: true,
    totalAmount: 3066,
    driverEarning: 2300,
    commission: 766,
    reviews: 126,
    rating: 5,
    partnerHidden: true,
  },
  {
    id: 'MK-1004',
    name: 'Travel Partner',
    when: 'Today',
    time: '12:15 PM',
    from: 'New Delhi',
    to: 'Aligarh',
    pickupFrom: 'New Delhi, Delhi, India',
    dropTo: 'Aligarh, Uttar Pradesh, India',
    tripType: 'One Way',
    vehicle: 'Ertiga',
    vehicleType: 'ertiga',
    extras: 'with carrier, All inclusive, Inc Airport Parking',
    bookingType: 'Public Booking',
    secured: true,
    totalAmount: 3300,
    driverEarning: 2000,
    commission: 1300,
    reviews: 12,
    rating: 4.5,
    partnerHidden: true,
  },
];

export const mockMyBookings = [
  {
    id: '7313',
    dateTime: 'Jan 01, 2023 @ 09:00 PM',
    status: 'Assigned',
    from: 'Dehradun',
    to: 'Mussoorie',
    vehicle: 'Sedan',
    pricingNote: 'All inclusive',
    amount: 1200,
    tripType: 'ONE WAY',
    tab: 'posted',
  },
  {
    id: '7314',
    dateTime: 'Jan 02, 2023 @ 07:30 AM',
    status: 'Assigned',
    from: 'Dehradun',
    to: 'Mussoorie',
    vehicle: 'Sedan',
    pricingNote: 'All inclusive',
    amount: 1200,
    tripType: 'ONE WAY',
    tab: 'posted',
  },
  {
    id: '7315',
    dateTime: 'Jan 03, 2023 @ 11:00 AM',
    status: 'Assigned',
    from: 'Dehradun',
    to: 'Mussoorie',
    vehicle: 'Sedan',
    pricingNote: 'All inclusive',
    amount: 1200,
    tripType: 'ONE WAY',
    tab: 'posted',
  },
  {
    id: '8201',
    dateTime: 'Jan 05, 2023 @ 10:00 AM',
    status: 'Pending',
    from: 'Delhi',
    to: 'Agra',
    vehicle: 'Innova',
    pricingNote: 'All inclusive',
    amount: 4500,
    tripType: 'ROUND TRIP',
    tab: 'received',
  },
];

export const mockFreeVehicles = [
  {
    id: 'FV-1001',
    vehicleType: 'Ertiga',
    availableFromDate: 'Today',
    availableFromTime: '01:00 PM',
    availableTillDate: 'Tomorrow',
    availableTillTime: '06:00 PM',
    location: 'Bareilly, उत्तर प्रदेश, भारत',
    otherDetails: '-',
    currentLocationOnly: true,
    name: 'Kunwarpal',
    company: 'Jay shree kirsana travels',
    verified: true,
    hasAvatar: true,
  },
  {
    id: 'FV-1002',
    vehicleType: 'Sedan',
    availableFromDate: 'Today',
    availableFromTime: '04:24 PM',
    availableTillDate: 'Tomorrow',
    availableTillTime: '04:28 PM',
    location: 'Adil Nagar, Lucknow, Uttar Pradesh, India',
    otherDetails:
      'kisi v bhai to lucknow se all over india kahi v jana ho to contact kre sedan car hai carrier ke sath 9170337201',
    name: 'Gita devi',
    company: 'Tour and travels',
    verified: true,
    phone: '9170337201',
    hasAvatar: true,
  },
  {
    id: 'FV-1003',
    vehicleType: 'Sedan',
    availableFromDate: 'Sep 18, 2026',
    availableFromTime: '10:00 AM',
    availableTillDate: 'Sep 18, 2026',
    availableTillTime: '08:00 PM',
    location: 'Mansarovar, जयपुर, राजस्थान, भारत',
    otherDetails: 'tonk Sawai Madhopur ke liye call kre 9414653454',
    name: 'Mr Lakhan',
    company: "Amrita tour's",
    verified: true,
    phone: '9414653454',
    hasAvatar: true,
  },
  {
    id: 'FV-1004',
    vehicleType: 'Sedan',
    availableFromDate: 'Today',
    availableFromTime: '11:25 AM',
    availableTillDate: 'Today',
    availableTillTime: '11:25 AM',
    location:
      'Nawalgarh Road, Azad Nagar, Kishan Colony, Jat Colony, Sikar, Rajasthan, India',
    otherDetails: 'Nawalgarth sikar to jaipur ajmer gurugram delhi airport',
    name: 'INDRAJ',
    company: 'Choudhary ture trewal',
    verified: true,
    hasAvatar: true,
  },
  {
    id: 'FV-1005',
    vehicleType: 'Sedan',
    availableFromDate: 'Today',
    availableFromTime: '03:18 PM',
    availableTillDate: 'Sep 18, 2026',
    availableTillTime: '11:19 AM',
    location: 'Noida',
    otherDetails:
      'Noida or Greater Noida se Khatushyam Ji and Salasar Bala Ji\n\nJane Wale call kre 7390995460\nOne way- 4000/- or Round trip- 7500/- ke but Toll + border tax alag se lagega.\n\nDzire New model and without carrier 🚗',
    name: 'Travel Partner',
    company: 'Tour and travels',
    verified: true,
    phone: '7390995460',
    hasAvatar: true,
  },
];

export const mockChats = [
  {
    id: 'chat-001',
    tab: 'posted',
    contactName: 'namit',
    contactPhone: '+91 98765 43210',
    avatarInitials: 'NA',
    lastMessage: 'Driver Name\nContact Number\nVehicle Registration',
    lastMessageAt: 'Last Week',
    unreadCount: 0,
    booking: {
      id: '31613',
      dateTime: 'May 18, 2023 @ 05:18 PM',
      status: 'Ended',
      from: 'Agra',
      to: 'New Delhi',
      vehicle: 'Sedan',
      tripType: 'ONE WAY',
      amount: 3000,
      network: 'My Network',
      completedBy: 'NAMIT',
    },
    messages: [
      {
        id: 'm1',
        type: 'images',
        sender: 'them',
        time: '05:20 PM',
        images: [
          {label: 'Driver', color: '#5B6B7A'},
          {label: 'Front', color: '#3D4A5C'},
          {label: 'Side', color: '#2F3A48'},
          {label: 'Rear', color: '#4A5563'},
        ],
      },
      {
        id: 'm2',
        type: 'text',
        sender: 'them',
        time: '05:21 PM',
        text: 'Driver Name\nContact Number\nVehicle Registration\nVehicle Type',
      },
    ],
  },
  {
    id: 'chat-002',
    tab: 'posted',
    contactName: 'Deepesh Dutta',
    contactPhone: '+91 91234 56780',
    avatarInitials: 'DD',
    lastMessage: 'Vehicle is ready at pickup point',
    lastMessageAt: 'Yesterday',
    unreadCount: 2,
    booking: {
      id: '7313',
      dateTime: 'Jan 01, 2023 @ 09:00 PM',
      status: 'Assigned',
      from: 'Dehradun',
      to: 'Mussoorie',
      vehicle: 'Sedan',
      tripType: 'ONE WAY',
      amount: 1200,
      network: 'My Network',
      completedBy: null,
    },
    messages: [
      {
        id: 'm1',
        type: 'text',
        sender: 'them',
        time: '08:45 PM',
        text: 'Hi, I can take this booking.',
      },
      {
        id: 'm2',
        type: 'text',
        sender: 'me',
        time: '08:50 PM',
        text: 'Please share driver and vehicle details.',
      },
      {
        id: 'm3',
        type: 'text',
        sender: 'them',
        time: '09:05 PM',
        text: 'Vehicle is ready at pickup point',
      },
    ],
  },
  {
    id: 'chat-003',
    tab: 'posted',
    contactName: 'Kunwarpal',
    contactPhone: '+91 99887 76655',
    avatarInitials: 'KU',
    lastMessage: 'Ok sir, reaching in 20 mins',
    lastMessageAt: '2 days ago',
    unreadCount: 0,
    booking: {
      id: '7314',
      dateTime: 'Jan 02, 2023 @ 07:30 AM',
      status: 'Assigned',
      from: 'Dehradun',
      to: 'Mussoorie',
      vehicle: 'Sedan',
      tripType: 'ONE WAY',
      amount: 1200,
      network: null,
      completedBy: null,
    },
    messages: [
      {
        id: 'm1',
        type: 'text',
        sender: 'them',
        time: '07:10 AM',
        text: 'Ok sir, reaching in 20 mins',
      },
    ],
  },
  {
    id: 'chat-101',
    tab: 'received',
    contactName: 'Priya Sharma',
    contactPhone: '+91 98111 22334',
    avatarInitials: 'PS',
    lastMessage: 'Please confirm the fare once',
    lastMessageAt: 'Today',
    unreadCount: 1,
    booking: {
      id: '8201',
      dateTime: 'Jan 05, 2023 @ 10:00 AM',
      status: 'Pending',
      from: 'Delhi',
      to: 'Agra',
      vehicle: 'Innova',
      tripType: 'ROUND TRIP',
      amount: 4500,
      network: 'My Network',
      completedBy: null,
    },
    messages: [
      {
        id: 'm1',
        type: 'text',
        sender: 'them',
        time: '09:40 AM',
        text: 'Hi, is this booking still available?',
      },
      {
        id: 'm2',
        type: 'text',
        sender: 'me',
        time: '09:55 AM',
        text: 'Yes, Innova is free for this trip.',
      },
      {
        id: 'm3',
        type: 'text',
        sender: 'them',
        time: '10:05 AM',
        text: 'Please confirm the fare once',
      },
    ],
  },
  {
    id: 'chat-102',
    tab: 'received',
    contactName: 'Amit Verma',
    contactPhone: '+91 90000 11122',
    avatarInitials: 'AV',
    lastMessage: 'Thanks, booking completed.',
    lastMessageAt: '3 days ago',
    unreadCount: 0,
    booking: {
      id: '8202',
      dateTime: 'Jan 04, 2023 @ 06:00 PM',
      status: 'Ended',
      from: 'Gurugram',
      to: 'Jaipur',
      vehicle: 'Innova',
      tripType: 'ONE WAY',
      amount: 9500,
      network: null,
      completedBy: 'AMIT VERMA',
    },
    messages: [
      {
        id: 'm1',
        type: 'text',
        sender: 'them',
        time: '05:30 PM',
        text: 'Driver Name\nContact Number\nVehicle Registration\nVehicle Type',
      },
      {
        id: 'm2',
        type: 'text',
        sender: 'me',
        time: '06:10 PM',
        text: 'Thanks, booking completed.',
      },
    ],
  },
];

export const getChatById = id => mockChats.find(chat => chat.id === id);

export const getChatByBookingId = bookingId =>
  mockChats.find(chat => String(chat.booking?.id) === String(bookingId));

export const mockTransactions = [
  {
    id: '3216758',
    type: 'Booking Posted',
    status: 'SUCCESS',
    day: '31',
    monthYear: 'AUG, 2026',
    time: '08:32 PM',
    bookingAmount: 6000.0,
    commission: 500.0,
    platformCharges: 17.5,
    earning: 482.5,
  },
  {
    id: '3216333',
    type: 'Booking Posted',
    status: 'FAILED',
    day: '31',
    monthYear: 'AUG, 2026',
    time: '08:32 PM',
    bookingAmount: 6000.0,
    commission: 500.0,
    platformCharges: 17.5,
    earning: 482.5,
  },
  {
    id: '3216295',
    type: 'Booking Posted',
    status: 'REFUNDED',
    day: '31',
    monthYear: 'AUG, 2026',
    time: '08:32 PM',
    bookingAmount: 6000.0,
    commission: 500.0,
    platformCharges: 0.0,
    earning: 500.0,
  },
];

export const mockNetworkContacts = [
  {
    id: 'net-1',
    name: 'Namit jio',
    phones: ['999 999 9999'],
    status: 'Member since Nov 04, 2022',
  },
  {
    id: 'net-2',
    name: 'Uttarakhand Musafir Dehradun',
    phones: ['9389173930'],
    status: 'Member since Nov 06, 2022',
  },
  {
    id: 'net-3',
    name: '',
    phones: ['999 999 9999', '8979752339'],
    status: 'Member since Jul 17, 2022',
  },
  {
    id: 'net-4',
    name: 'Rahul',
    phones: ['7456960945', '999 999 9999'],
    status: 'Member since Jul 16, 2022',
  },
  {
    id: 'net-5',
    name: 'KP Bhaiya',
    phones: ['0821804495'],
    status: 'Invitation Sent On Nov 06, 2022',
  },
  {
    id: 'net-6',
    name: 'Monu Bahuguna Taxi',
    phones: ['9897219634', '999 999 9999'],
    status: 'Aug 27, 2022',
  },
];

export default {
  mockUsers,
  mockBookings,
  mockMarketBookings,
  mockMyBookings,
  mockFreeVehicles,
  mockChats,
  getChatById,
  getChatByBookingId,
  mockTransactions,
  mockNetworkContacts,
};
