const Images = {
  addDriver: require('../assets/images/AddDriver.png'),
  addVehicle: require('../assets/images/AddVehicle.png'),
  bookingBanner: require('../assets/images/BokingBanner.png'),
  carImage: require('../assets/images/carImage.png'),
  carErtiga: require('../assets/images/car_ertiga.png'),
  carInnova: require('../assets/images/car_innova.png'),
  carSedan: require('../assets/images/car_sedan.png'),
  delhi: require('../assets/images/Delhi.jpeg'),
  delhiJpg: require('../assets/images/Delhi.jpg'),
  delhiPng: require('../assets/images/Delhi.png'),
  headerImage: require('../assets/images/HeaderImage.png'),
  headerBanner2: require('../assets/images/HeaderBanner2.png'),
  locationIcon: require('../assets/icons/location.png'),
  timeIcon: require('../assets/icons/TimeIcon.png'),
  bookingIcon: require('../assets/icons/bookingIcon.png'),
  freeVehiclesIcon: require('../assets/icons/FreeVehiclesIcon.png'),
  filterIcon: require('../assets/icons/FilterIcon.png'),
  notificationIcon: require('../assets/icons/NotificationIcon.png'),
  carInsuranceIcon: require('../assets/icons/carInsuranceIcon.png'),
  tutorialVideoIcon: require('../assets/icons/TutorialVideoIcon.png'),
  rulesRegulationIcon: require('../assets/icons/Rules&regulationIcon.png'),
  haryana: require('../assets/images/Haryana.jpeg'),
  haryana1: require('../assets/images/Haryana1.jpg'),
  innova: require('../assets/images/Innova.webp'),
  loginImage: require('../assets/images/LoginImage .png'),
  authSheetWave: require('../assets/images/auth-sheet-wave.png'),
  authSheetFooter: require('../assets/images/auth-sheet-footer.png'),
  introDriver1: require('../assets/images/intro-driver-1.png'),
  introDriver2: require('../assets/images/intro-driver-2.png'),
  introDriver3: require('../assets/images/intro-driver-3.png'),
  partnerDeepesh: require('../assets/images/partner_deepesh.png'),
  profile: require('../assets/images/Profile.png'),
  personalInfo: require('../assets/images/PersonalInfo.png'),
  rajasthan: require('../assets/images/Rajasthan.jpeg'),
  rajasthanJpg: require('../assets/images/Rajasthan.jpg'),
  rajasthanPng: require('../assets/images/Rajasthan.png'),
  staySafeBanner: require('../assets/images/StaySafeBanner.png'),
  uttarakhand: require('../assets/images/Uttarakhand.jpeg'),
  uttarakhand1: require('../assets/images/Uttarakhand1.jpeg'),
};

export default Images;
export {Images};
