export const MARKET_TOUR_STEPS = [
  {
    id: 'welcome',
    art: 'welcome',
    title: 'Welcome to Tajway!',
    body: "India's Largest B2B Taxi\nCommunity",
    cta: 'Start Setup',
    showVolume: false,
    speech:
      'ताजवे में आपका स्वागत है। यह भारत की बड़ी बी टू बी टैक्सी कम्युनिटी है। यहाँ आप बुकिंग देख सकते हैं और अपनी राइड पोस्ट कर सकते हैं।',
  },
  {
    id: 'bookings',
    art: 'bookings',
    artCaption: 'Taxi Marketplace',
    target: 'booking',
    placement: 'above',
    radius: 20,
    title: 'Get Taxi Bookings\nanytime',
    body: 'Checkout entire Taxi\nMarketplace here',
    cta: 'Next',
    showVolume: true,
    speech:
      'यहाँ पूरी टैक्सी मार्केटप्लेस दिखती है। आप वन वे और राउंड ट्रिप बुकिंग कभी भी देख सकते हैं। पसंद की बुकिंग पर बेस्ट प्राइस कोट कर सकते हैं।',
  },
  {
    id: 'profile',
    art: 'profile',
    artCaption: 'Complete Setup to Start Booking',
    target: 'vehicle',
    fallback: 'progress',
    placement: 'above',
    radius: 18,
    title: 'Verify your profile',
    body: 'complete your verification in\norder to start getting bookings',
    cta: 'Next',
    showVolume: false,
    speech:
      'बुकिंग लेने से पहले प्रोफाइल वेरिफाई करना जरूरी है। कम से कम एक गाड़ी और एक ड्राइवर ऐड करें। इसके बिना आप बुकिंग नहीं ले पाएंगे।',
  },
  {
    id: 'videos',
    art: 'videos',
    target: 'videos',
    placement: 'below',
    shape: 'round',
    radius: 16,
    title: 'How to Use?',
    body: 'Watch quick tutorials anytime.',
    cta: 'Next',
    showVolume: true,
    speech:
      'ट्यूटोरियल वीडियो से ऐप इस्तेमाल करना सीखें। वॉल्यूम बढ़ाकर ये वीडियो कभी भी देख सकते हैं। हर सेक्शन का छोटा डेमो यहाँ मिलेगा।',
  },
  {
    id: 'alerts',
    art: 'alerts',
    artCaption: 'Set your alerts now',
    target: 'alerts',
    fixed: true,
    placement: 'below',
    shape: 'pill',
    title: 'Get Booking\nNotifications',
    body: 'Set alerts now.',
    cta: 'Next',
    showVolume: true,
    speech:
      'अलर्ट ऑन करें ताकि नई बुकिंग आते ही नोटिफिकेशन मिले। अपने रूट के हिसाब से अलर्ट सेट कर सकते हैं। सही बुकिंग मिस नहीं होगी।',
  },
  {
    id: 'filter',
    art: 'filter',
    artCaption: 'Filter Bookings.',
    target: 'filter',
    placement: 'below',
    shape: 'round',
    radius: 14,
    title: 'Filter Bookings',
    body: 'Find relevant bookings by trip\ntype, route, and vehicle.',
    cta: 'Next',
    showVolume: true,
    speech:
      'फिल्टर से ट्रिप टाइप, रूट और गाड़ी के हिसाब से सिर्फ सही बुकिंग देखें। इससे मार्केटप्लेस जल्दी समझ में आती है।',
  },
  {
    id: 'post',
    art: 'post',
    artCaption: 'Post bookings',
    target: 'post',
    placement: 'above',
    shape: 'circle',
    title: 'Post a booking in\nminutes',
    body: 'Connect with verified drivers\nand earn better commissions.',
    cta: 'Next',
    showVolume: false,
    speech:
      'नीचे प्लस बटन से मिनटों में बुकिंग पोस्ट करें। वेरिफाइड ड्राइवर जुड़ेंगे और आपको बेहतर कमीशन मिल सकता है।',
  },
  {
    id: 'help',
    art: 'help',
    artCaption: '24x7 Support Available',
    target: 'help',
    fixed: true,
    placement: 'below',
    shape: 'pill',
    title: 'Need help?',
    body: 'Click here to call us anytime\nOur support team is available\n24×7.',
    cta: 'Done',
    showVolume: true,
    speech:
      'मदद चाहिए तो हेल्प दबाएं। हमारी सपोर्ट टीम चौबीस घंटे उपलब्ध है। कभी भी कॉल कर सकते हैं।',
  },
];
